// THIS FILE WAS GENERATED BY THE OAK FLOW TOOL
package main

import (
	json "encoding/json"
	fmt "fmt"
	os "os"
)

func main() {

	var decode = func() interface{} {
		var v interface{}
		dec := json.NewDecoder(os.Stdin)
		dec.UseNumber()
		dec.Decode(&v)
		return v
	}

	var encode = func(v interface{}) string {
		buf, _ := json.MarshalIndent(v, "", "\t")
		return string(buf)
	}

	var print = fmt.Println

	v := decode()

	a := encode(v)

	print(a)

}
