
// generated by gocc; DO NOT EDIT.

package parser

type(
	actionTable [numStates]actionRow
	actionRow struct {
		canRecover bool
		actions [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(1),		/* $, reduce: Pipeline */
			nil,		/* empty */
			nil,		/* ; */
			shift(4),		/* component */
			nil,		/* id */
			nil,		/* () */
			shift(5),		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S1
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			accept(true),		/* $ */
			nil,		/* empty */
			nil,		/* ; */
			nil,		/* component */
			nil,		/* id */
			nil,		/* () */
			nil,		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S2
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* empty */
			shift(6),		/* ; */
			nil,		/* component */
			nil,		/* id */
			nil,		/* () */
			nil,		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S3
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* empty */
			shift(7),		/* ; */
			nil,		/* component */
			nil,		/* id */
			nil,		/* () */
			nil,		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S4
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* empty */
			nil,		/* ; */
			nil,		/* component */
			shift(8),		/* id */
			nil,		/* () */
			nil,		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S5
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* empty */
			nil,		/* ; */
			nil,		/* component */
			shift(9),		/* id */
			nil,		/* () */
			nil,		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S6
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(1),		/* $, reduce: Pipeline */
			nil,		/* empty */
			nil,		/* ; */
			shift(4),		/* component */
			nil,		/* id */
			nil,		/* () */
			shift(5),		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S7
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(1),		/* $, reduce: Pipeline */
			nil,		/* empty */
			nil,		/* ; */
			shift(4),		/* component */
			nil,		/* id */
			nil,		/* () */
			shift(5),		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S8
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* empty */
			nil,		/* ; */
			nil,		/* component */
			shift(12),		/* id */
			nil,		/* () */
			nil,		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S9
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* empty */
			nil,		/* ; */
			nil,		/* component */
			nil,		/* id */
			nil,		/* () */
			nil,		/* connect */
			shift(13),		/* . */
			
		},

	},
	actionRow{ // S10
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(2),		/* $, reduce: Pipeline */
			nil,		/* empty */
			nil,		/* ; */
			nil,		/* component */
			nil,		/* id */
			nil,		/* () */
			nil,		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S11
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(3),		/* $, reduce: Pipeline */
			nil,		/* empty */
			nil,		/* ; */
			nil,		/* component */
			nil,		/* id */
			nil,		/* () */
			nil,		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S12
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* empty */
			nil,		/* ; */
			nil,		/* component */
			nil,		/* id */
			shift(14),		/* () */
			nil,		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S13
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* empty */
			nil,		/* ; */
			nil,		/* component */
			shift(15),		/* id */
			nil,		/* () */
			nil,		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S14
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* empty */
			reduce(4),		/* ;, reduce: Component */
			nil,		/* component */
			nil,		/* id */
			nil,		/* () */
			nil,		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S15
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* empty */
			nil,		/* ; */
			nil,		/* component */
			shift(16),		/* id */
			nil,		/* () */
			nil,		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S16
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* empty */
			nil,		/* ; */
			nil,		/* component */
			nil,		/* id */
			nil,		/* () */
			nil,		/* connect */
			shift(17),		/* . */
			
		},

	},
	actionRow{ // S17
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* empty */
			nil,		/* ; */
			nil,		/* component */
			shift(18),		/* id */
			nil,		/* () */
			nil,		/* connect */
			nil,		/* . */
			
		},

	},
	actionRow{ // S18
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* empty */
			reduce(5),		/* ;, reduce: Connection */
			nil,		/* component */
			nil,		/* id */
			nil,		/* () */
			nil,		/* connect */
			nil,		/* . */
			
		},

	},
	
}

