
// generated by gocc; DO NOT EDIT.

package parser

type(
	actionTable [numStates]actionRow
	actionRow struct {
		canRecover bool
		actions [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(4),		/* $, reduce: Pipeline */
			shift(4),		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			shift(7),		/* component */
			nil,		/* , */
			shift(8),		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S1
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			accept(true),		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S2
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(4),		/* $, reduce: Pipeline */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			shift(7),		/* component */
			nil,		/* , */
			shift(8),		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S3
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(2),		/* $, reduce: Program */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S4
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			shift(10),		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S5
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			shift(11),		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S6
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			shift(12),		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S7
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			shift(13),		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S8
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			shift(14),		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S9
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(1),		/* $, reduce: Program */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S10
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			shift(15),		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S11
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(4),		/* $, reduce: Pipeline */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			shift(7),		/* component */
			nil,		/* , */
			shift(8),		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S12
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(4),		/* $, reduce: Pipeline */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			shift(7),		/* component */
			nil,		/* , */
			shift(8),		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S13
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			shift(18),		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S14
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			shift(19),		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S15
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			shift(20),		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S16
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(5),		/* $, reduce: Pipeline */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S17
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(6),		/* $, reduce: Pipeline */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S18
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			shift(21),		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S19
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			shift(22),		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S20
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			shift(23),		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S21
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			reduce(8),		/* ), reduce: PossiblyEmptyArgList */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			shift(30),		/* string_lit */
			shift(31),		/* int_lit */
			shift(32),		/* true */
			shift(33),		/* false */
			
		},

	},
	actionRow{ // S22
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			shift(34),		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S23
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(3),		/* $, reduce: Frontend */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			reduce(3),		/* component, reduce: Frontend */
			nil,		/* , */
			reduce(3),		/* connect, reduce: Frontend */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S24
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			shift(35),		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S25
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			reduce(9),		/* ), reduce: PossiblyEmptyArgList */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S26
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			reduce(10),		/* ), reduce: ArgList */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			shift(36),		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S27
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			reduce(13),		/* ), reduce: Value */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			reduce(13),		/* ,, reduce: Value */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S28
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			reduce(14),		/* ), reduce: Value */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			reduce(14),		/* ,, reduce: Value */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S29
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			reduce(15),		/* ), reduce: Value */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			reduce(15),		/* ,, reduce: Value */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S30
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			reduce(16),		/* ), reduce: String */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			reduce(16),		/* ,, reduce: String */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S31
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			reduce(17),		/* ), reduce: Int */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			reduce(17),		/* ,, reduce: Int */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S32
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			reduce(18),		/* ), reduce: Bool */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			reduce(18),		/* ,, reduce: Bool */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S33
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			reduce(19),		/* ), reduce: Bool */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			reduce(19),		/* ,, reduce: Bool */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S34
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			shift(37),		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S35
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			reduce(7),		/* ;, reduce: Component */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S36
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			shift(30),		/* string_lit */
			shift(31),		/* int_lit */
			shift(32),		/* true */
			shift(33),		/* false */
			
		},

	},
	actionRow{ // S37
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			shift(39),		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S38
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			reduce(11),		/* ), reduce: ArgList */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S39
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			shift(40),		/* id */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* ; */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S40
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* frontend */
			nil,		/* id */
			nil,		/* ( */
			nil,		/* ) */
			reduce(12),		/* ;, reduce: Connection */
			nil,		/* empty */
			nil,		/* component */
			nil,		/* , */
			nil,		/* connect */
			nil,		/* dot */
			nil,		/* to */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	
}

