
// generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 13
type(
	gotoTable [numStates]gotoRow
	gotoRow	[numNTSymbols] int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		
		-1, // S'
		1, // Program
		2, // Frontend
		3, // Pipeline
		5, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		6, // Connection
		7, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S1
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S2
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		11, // Pipeline
		5, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		6, // Connection
		7, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S3
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S4
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S5
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S6
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S7
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S8
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S9
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S10
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		18, // Value
		19, // String
		20, // Int
		21, // Bool
		

	},
	gotoRow{ // S11
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S12
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S13
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		27, // Pipeline
		5, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		6, // Connection
		7, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S14
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		28, // Pipeline
		5, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		6, // Connection
		7, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S15
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		29, // Pipeline
		5, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		6, // Connection
		7, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S16
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S17
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S18
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S19
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S20
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S21
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S22
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S23
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S24
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S25
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S26
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S27
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S28
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S29
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S30
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S31
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S32
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S33
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S34
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		38, // PossiblyEmptyArgList
		39, // ArgList
		-1, // Connection
		-1, // Constant
		40, // Value
		41, // String
		42, // Int
		43, // Bool
		

	},
	gotoRow{ // S35
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S36
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S37
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S38
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S39
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S40
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S41
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S42
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S43
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S44
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S45
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S46
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S47
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S48
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S49
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S50
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S51
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		54, // ArgList
		-1, // Connection
		-1, // Constant
		40, // Value
		41, // String
		42, // Int
		43, // Bool
		

	},
	gotoRow{ // S52
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S53
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S54
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S55
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S56
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Constant
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	
}
