
// generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 12
type(
	gotoTable [numStates]gotoRow
	gotoRow	[numNTSymbols] int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		
		-1, // S'
		1, // Program
		2, // Frontend
		3, // Pipeline
		5, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		6, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S1
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S2
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		9, // Pipeline
		5, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		6, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S3
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S4
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S5
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S6
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S7
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S8
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S9
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S10
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S11
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		16, // Pipeline
		5, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		6, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S12
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		17, // Pipeline
		5, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		6, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S13
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S14
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S15
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S16
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S17
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S18
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S19
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S20
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S21
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		24, // PossiblyEmptyArgList
		25, // ArgList
		-1, // Connection
		26, // Value
		27, // String
		28, // Int
		29, // Bool
		

	},
	gotoRow{ // S22
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S23
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S24
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S25
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S26
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S27
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S28
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S29
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S30
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S31
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S32
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S33
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S34
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S35
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S36
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		38, // ArgList
		-1, // Connection
		26, // Value
		27, // String
		28, // Int
		29, // Bool
		

	},
	gotoRow{ // S37
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S38
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S39
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	gotoRow{ // S40
		
		-1, // S'
		-1, // Program
		-1, // Frontend
		-1, // Pipeline
		-1, // Component
		-1, // PossiblyEmptyArgList
		-1, // ArgList
		-1, // Connection
		-1, // Value
		-1, // String
		-1, // Int
		-1, // Bool
		

	},
	
}
