
// generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 4
type(
	gotoTable [numStates]gotoRow
	gotoRow	[numNTSymbols] int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		
		-1, // S'
		1, // Pipeline
		2, // Component
		3, // Connection
		

	},
	gotoRow{ // S1
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	gotoRow{ // S2
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	gotoRow{ // S3
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	gotoRow{ // S4
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	gotoRow{ // S5
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	gotoRow{ // S6
		
		-1, // S'
		10, // Pipeline
		2, // Component
		3, // Connection
		

	},
	gotoRow{ // S7
		
		-1, // S'
		11, // Pipeline
		2, // Component
		3, // Connection
		

	},
	gotoRow{ // S8
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	gotoRow{ // S9
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	gotoRow{ // S10
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	gotoRow{ // S11
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	gotoRow{ // S12
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	gotoRow{ // S13
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	gotoRow{ // S14
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	gotoRow{ // S15
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	gotoRow{ // S16
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	gotoRow{ // S17
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	gotoRow{ // S18
		
		-1, // S'
		-1, // Pipeline
		-1, // Component
		-1, // Connection
		

	},
	
}
