package flow

var templateSource = `

{{define "imports"}}
import (
{{range $k, $v := .Imports}}
	{{$k}} "{{$v}}"
{{- end}}
)
{{end}}

{{define "flowApp"}}
	// THIS FILE WAS GENERATED BY THE OAK FLOW TOOL
	package main

	{{template "imports" .App}}

	func main() {
		{{range .App.Components}}
		var {{.Label}} = {{.Func}}
		{{- end}}

		{{$root := .App}}

		{{range .Steps}}
		{{with .LHS}}{{. | join}} := {{end}}{{.Func}}({{.Args | join}})
		{{end}}
	}

{{end}}

{{define "typeChecker"}}

	package flow
	{{template "imports" .}}

	{{range $name, $comp := .Components}}
	var {{$name}} = {{$comp}}
	{{- end}}

{{end}}

`
