
// generated by gocc; DO NOT EDIT.

package lexer



/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates] func(rune) int

var TransTab = TransitionTable{
	
		// S0
		func(r rune) int {
			switch {
			case r == 9 : // ['\t','\t']
				return 1
			case r == 10 : // ['\n','\n']
				return 1
			case r == 13 : // ['\r','\r']
				return 1
			case r == 32 : // [' ',' ']
				return 1
			case r == 40 : // ['(','(']
				return 2
			case r == 46 : // ['.','.']
				return 3
			case r == 59 : // [';',';']
				return 4
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 98 : // ['a','b']
				return 5
			case r == 99 : // ['c','c']
				return 6
			case 100 <= r && r <= 122 : // ['d','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S1
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S2
		func(r rune) int {
			switch {
			case r == 41 : // [')',')']
				return 7
			
			
			
			}
			return NoState
			
		},
	
		// S3
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S4
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S5
		func(r rune) int {
			switch {
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 122 : // ['a','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S6
		func(r rune) int {
			switch {
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 110 : // ['a','n']
				return 5
			case r == 111 : // ['o','o']
				return 8
			case 112 <= r && r <= 122 : // ['p','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S7
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S8
		func(r rune) int {
			switch {
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 108 : // ['a','l']
				return 5
			case r == 109 : // ['m','m']
				return 9
			case r == 110 : // ['n','n']
				return 10
			case 111 <= r && r <= 122 : // ['o','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S9
		func(r rune) int {
			switch {
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 111 : // ['a','o']
				return 5
			case r == 112 : // ['p','p']
				return 11
			case 113 <= r && r <= 122 : // ['q','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S10
		func(r rune) int {
			switch {
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 109 : // ['a','m']
				return 5
			case r == 110 : // ['n','n']
				return 12
			case 111 <= r && r <= 122 : // ['o','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S11
		func(r rune) int {
			switch {
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 110 : // ['a','n']
				return 5
			case r == 111 : // ['o','o']
				return 13
			case 112 <= r && r <= 122 : // ['p','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S12
		func(r rune) int {
			switch {
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 100 : // ['a','d']
				return 5
			case r == 101 : // ['e','e']
				return 14
			case 102 <= r && r <= 122 : // ['f','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S13
		func(r rune) int {
			switch {
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 109 : // ['a','m']
				return 5
			case r == 110 : // ['n','n']
				return 15
			case 111 <= r && r <= 122 : // ['o','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S14
		func(r rune) int {
			switch {
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 98 : // ['a','b']
				return 5
			case r == 99 : // ['c','c']
				return 16
			case 100 <= r && r <= 122 : // ['d','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S15
		func(r rune) int {
			switch {
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 100 : // ['a','d']
				return 5
			case r == 101 : // ['e','e']
				return 17
			case 102 <= r && r <= 122 : // ['f','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S16
		func(r rune) int {
			switch {
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 115 : // ['a','s']
				return 5
			case r == 116 : // ['t','t']
				return 18
			case 117 <= r && r <= 122 : // ['u','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S17
		func(r rune) int {
			switch {
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 109 : // ['a','m']
				return 5
			case r == 110 : // ['n','n']
				return 19
			case 111 <= r && r <= 122 : // ['o','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S18
		func(r rune) int {
			switch {
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 122 : // ['a','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S19
		func(r rune) int {
			switch {
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 115 : // ['a','s']
				return 5
			case r == 116 : // ['t','t']
				return 20
			case 117 <= r && r <= 122 : // ['u','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S20
		func(r rune) int {
			switch {
			case 65 <= r && r <= 90 : // ['A','Z']
				return 5
			case 97 <= r && r <= 122 : // ['a','z']
				return 5
			
			
			
			}
			return NoState
			
		},
	
}
