/* Lexical Part */

_letter : 'a' - 'z' | 'A' - 'Z';

id : _letter {_letter} ;

!whitespace : ' ' | '\t' | '\n' | '\r' ;

/* Syntax Part */

<< import "github.com/Logiraptor/oak/flow/language/ast" >>

Pipeline:
    empty <<ast.Pipeline{}, nil>>
    | Component ";" Pipeline <<ast.AddComponent($2, $0), nil>>
    | Connection ";" Pipeline <<ast.AddConnection($2, $0), nil>>;

Component:
    "component" id id "()" << ast.NewComponent($1, $2), nil >>;

Connection:
    "connect" id "." id id "." id << ast.NewConnection($1, $3, $4, $6), nil >>;
